# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ushir (Rishi) Raval
tagline:          'Computer Scientist'
description:      'Computer Scientist'
url:              https://urishiraval.github.io/
baseurl:          /
cdn:              https://github.com/urishiraval/urishiraval.github.io/blob/gh-pages/


author:
  name:           'Rishi Raval'
  url:            https://urishiraval.github.io

paginate:         10
paginate_path: "/blog/:num"

# Custom vars
version:          2.1.0

socials:
  github:         https://github.com/urishiraval
  linkedin:       https://www.linkedin.com/in/unraval/
  instagram:      https://www.instagram.com/rishi_raval7/

github:
  repo:           https://github.com/urishiraval/urishiraval.github.io

plugins:
    - jekyll-paginate
